stages:
  - test

.test rust:
  image: rust
  stage: test
  before_script:
    - rustup default nightly
    - rustup update nightly

test thumbv7m build:
  extends: .test rust
  script:
    - rustup target add thumbv7m-none-eabi
    - cargo build --target thumbv7m-none-eabi --no-default-features --features alloc

test std:
  extends: .test rust
  script:
    - cargo test --no-default-features --features std

test alloc:
  extends: .test rust
  script:
    - cargo test --no-default-features --features alloc
